// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwghmxdnrrtwcaomuhmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3Z2hteGRucnJ0d2Nhb211aG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTg3ODksImV4cCI6MjA4ODIzNDc4OX0.qImVMzKX4IuA05FILP5QcziZ46KKXoFyp9S5GkiyTtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});